parameters:
    csm_poc.verse.content_type_identifier: verse

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\CSMBundle\Controller\VerseController:
        arguments:
            $docbookToXhtml5EditConverter: '@ezrichtext.converter.edit.xhtml5'
            $verseContentTypeIdentifier: '%csm_poc.verse.content_type_identifier%'

    EzSystems\CSMBundle\EventListener\MenuListener:
        tags:
            - { name: kernel.event_subscriber }